#This workflow will automatically test code in this repo

#name of the workflow
name: CI

#events which trigger a certain workflow
# (every time someone pushes to the main branch,
# or someone pulls from the main branch, the 'jobs' will get executed)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
#this specifies that we want to test it with two compilers

#all actions are listed here =>   https://github.com/actions
jobs:
  test:
    runs-on: windows-latest
    steps:
        #this gets the code 
      - name: Check out the code
        uses: actions/checkout@v1
      
        #this sets up the gcc compiler
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      
        #this installs qt framework
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

        #this executes the unit tests
      - name: Run QMake
        env:
          CC: ${{ matrix.compiler }}
        run: qmake tests/unit_test.cpp
